on:
  schedule:
    - cron: "10 0 * * *" # Every day at 12:10AM UTC
  workflow_dispatch:
permissions:
  id-token: write
  contents: write
name: Refresh Data
jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: NpmPackageCountSiteSession
          role-duration-seconds: 900
      - run: npm install
      - run: node grabStats.js > src/_data/stats.json
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DYNAMO_TABLE_NAME: ${{ secrets.DYNAMO_TABLE_NAME }}
      - run: node diffStats.js > src/_data/diff.json
      - name: Deploy Site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          npm run build

          wget https://github.com/lannonbr/netlify_deploy/releases/download/netlify_deploy-v0.3.0/netlify-deploy-linux-0.3.0.tar.gz
          tar -xvf netlify-deploy-linux-0.3.0.tar.gz

          ./release/netlify_deploy --path _site --prod
